### PR TITLE
[#32] geordi dump should stop on errors

### LINKED ISSUE #32: geordi dump should stop on errors
I executed `geordi dump production` recently where my postgres was set up in a wrong way (the database cluster was already on 9.6, where my pg binaries were still on version 9.5) which lead to an error while producing the dump:

```
geordi dump production

# Dumping the database of production
> Connecting to my.made-up-domain.de
> Dumping database for "production" environment ...
pg_dump: server version: 9.6.2; pg_dump version: 9.5.6
pg_dump: aborting because of server version mismatch
> Dumped to /home/made_up_user/dumps/dump_for_download.dump (0 KB)
Connection to my.made-up-domain.de closed.
> Downloading remote dump to tmp/production.dump ...
dump_for_download.dump                                                                                                                          100%    0     0.0KB/s   00:00

> Dumped the production database to tmp/production.dump.
```

Geordi continued execution after `pg_dump` failed with an error and downloaded an empty file to `tmp/production.dump`.
Instead, I would expect geordi to abort once the `pg_dump` command failed and immediately return with an error code.

### PR DESCRIPTION
**Pull request by tessi**
Attempt to fix #32

It turns out that `dumple` didn't check he return code of `mysqldump` or `pg_dump`.

I would have tested my change, but couldn't find existing tests for dumple :) So, I'll try to let it slip through. ;)

(Of course I manually checked that my changes work)

As always, a review would be very welcome.

### CODE REVIEW

**Comment by tessi** [comment]
@codener do you have time for a review?

**Comment by codener** [comment]
Hey @tessi, sorry that this dropped off my shelf. Code looks fine, I trust you tested it.

**Comment by codener** [comment]
Released as 1.6.4. Thanks!

**Comment by tessi** [comment]
thanks @codener ! 🎉

**Pull request merged**
