### PR TITLE
Change configuration handling for capistrano 3

### PR DESCRIPTION
**Pull request by bitboxer**
This is a first, naiv implementation. It works on the capistrano files we use at bitcrowd. 

There are no tests in this project, so I did not add one for this. I am pretty sure that you will
want something to change in this PR, so let's start discussing this :wink:

### CODE REVIEW

**Comment by henning-koch** [comment]
Thanks @bitboxer !

@codener Can you manually test the change with both Capistrano 2 and 3?

**Comment by bitboxer** [comment]
@codener if you need any help or see areas that need improvement, just ping me. I am happy to help to make this merge-able.

**Comment by bitboxer** [comment]
Sadly this PR has problems with Capistrano 2 :sob:

**Comment by codener** [comment]
It is increasingly important to support Capistrano 3. Thanks for pushing this forward!

However, Geordi definitely needs to support both Capistrano 2 and 3. Please make sure it works with both versions before we can merge this PR.

**Pull request closed without merging**
